#ansible-playbook -i ../TOKD3.11/ansible/inventory/hosts.yml playbooks/prerequisites.yml
OSEv3:
  vars:
    ansible_become: true
    openshift_deployment_type: origin

    openshift_disable_check: memory_availability,disk_availability,docker_image_availability
    openshift_enable_service_catalog: false
    template_service_broker_install: false
    openshift_logging_install_logging: false
    openshift_master_api_port: 443
    openshift_master_console_port: 443
    openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]
    openshift_master_htpasswd_users: {'admin': '$apr1$loVrqEaw$OSoPrbqB2ND8vRcC/cJkJ0', 'user': '$apr1$loVrqEaw$OSoPrbqB2ND8vRcC/cJkJ0'}
    openshift_master_cluster_method: native
    openshift_master_cluster_hostname: "{{ master_hostname }}.{{ default_subdomain }}" 
    openshift_master_cluster_public_hostname: "{{ master_hostname }}.{{ default_subdomain }}"  
    openshift_master_default_subdomain: "{{ default_subdomain }}"
    # etcd_ip: "{{ master_node_ip }}"
  children:
    masters:
      hosts:
        vag-master.aci.test.com:
    nodes:
      hosts:
        vag-master.aci.test.com:
        vag-node1.aci.test.com:
        vag-node2.aci.test.com:
    etcd:
      hosts:
        vag-master.aci.test.com:
all:
  vars:
    vagrant: true
    dns:
      primary: 208.67.220.220
      secondary: 208.67.222.222
    node_vlan: 4001
    infra_vlan: 4093
    master_node_ip: 10.1.0.11
    node1_node_ip: 10.1.0.12
    node2_node_ip: 10.1.0.13
    node_ip_gateway: 10.1.0.1
    node_ip_prefix: 16
    node_ip_network: 10.1.0.0
    local_install_ansible: false
    # local_install_ansible: true 
    # install_docker: false
    install_docker: true 
    ansible_python_interpreter: /usr/bin/env python
    default_subdomain: aci.test.com
    master_hostname: vag-master
    node1_hostname: vag-node1
    node2_hostname: vag-node2
    ocp_version: '3.11'
    docker_version: '1.13.1'

  children:
    vagnodes:
      hosts:
        vag-master.aci.test.com:
          ansible_ssh_port: 2222
          #在多网卡安装环境下，指定oc要绑定的服务地址，关系到etcd的监听地址以及数字证书的绑定地址
          # openshift_ip: "{{ master_node_ip }}"
          ansible_ssh_private_key_file: ~/Documents/Dev/TOKD3.11/.vagrant/machines/vag-master/virtualbox/private_key
          openshift_node_group_name: 'node-config-master'
          node: 
            ip: "{{ master_node_ip }}" 
            vlan:  "{{ node_vlan }}"
            prefix: "{{ node_ip_prefix }}" 
            network: "{{ node_ip_network }}" 
            gateway: "{{ node_ip_gateway }}" 
          # infra:
          #   ip: 192.168.1.200
          #   prefix: 24 
          #   network: 192.168.1.0
          #   gateway: 192.168.1.1
          #   vlan: 4093
        vag-node1.aci.test.com:
          ansible_ssh_port: 2200
          # openshift_ip: "{{ node1_node_ip }}" 
          ansible_ssh_private_key_file: ~/Documents/Dev/TOKD3.11/.vagrant/machines/vag-node1/virtualbox/private_key
          openshift_node_group_name: 'node-config-infra'
          node:
            ip: "{{ node1_node_ip }}" 
            vlan:  "{{ node_vlan }}"
            prefix: "{{ node_ip_prefix }}" 
            network: "{{ node_ip_network }}" 
            gateway: "{{ node_ip_gateway }}" 

        vag-node2.aci.test.com:
          ansible_ssh_port: 2201
          # openshift_ip: "{{ node2_node_ip }}" 
          ansible_ssh_private_key_file: ~/Documents/Dev/TOKD3.11/.vagrant/machines/vag-node2/virtualbox/private_key
          openshift_node_group_name: 'node-config-compute'
          node:
            ip: "{{ node2_node_ip }}" 
            vlan:  "{{ node_vlan }}"
            prefix: "{{ node_ip_prefix }}" 
            network: "{{ node_ip_network }}" 
            gateway: "{{ node_ip_gateway }}" 
      vars:
          ansible_ssh_host: 127.0.0.1
          ansible_user: vagrant 
          aci_interface: eth2
          mgmt:
              interface: eth0
              gatewey:
              
          infra:
            vlan: "{{ infra_vlan }}"  
          service:
            vlan: "{{ node_vlan }}" 


    devbox-group:
      hosts:
        devbox:
          ansible_host: 172.20.0.132
          ansible_user: developer


    kube:
      hosts:
        kube01:
          ansible_host: 172.20.0.133
          ansible_user: developer21
          aci_interface: ens224
          node:
            ip: 172.20.8.11
            prefix: 26
            network: 172.20.8.0
            gateway: 172.20.8.1
            vlan: 918
          infra:
            vlan: 4093
          service:
            vlan: 919
          mgmt:
            interface: ens192

        kube02:
          ansible_host: 172.20.0.134
          ansible_user: developer
          aci_interface: ens224
          node:
            ip: 172.20.8.12
            prefix: 26
            network: 172.20.8.0
            gateway: 172.20.8.1
            vlan: 918
          infra:
            vlan: 4093
          service:
            vlan: 919
          mgmt:
            interface: ens192

        kube03:
          ansible_host: 172.20.0.135
          ansible_user: developer
          aci_interface: ens224
          node:
            ip: 172.20.8.13
            prefix: 26
            network: 172.20.8.0
            gateway: 172.20.8.1
            vlan: 918
          infra:
            vlan: 4093
          service:
            vlan: 919
          mgmt:
            interface: ens192